version: '3'

services:
  stmchat_backend:
    image: stmchat_backend
    restart: always
    build:
      context: "."
      dockerfile: "backend.Dockerfile"
    ports:
      - "5000:80"
    volumes:
      - ./data/:/app/data
    networks:
      - stmchat
    

  stmchat_mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ExaMp1ePa55w02d
    ports:
      -  "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - stmchat

  stmchat_frontend:
    image: stmchat_frontend
    restart: always
    build:
      context: "."
      dockerfile: "frontend.Dockerfile"
    networks:
      - stmchat

  stmchat_nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginxconf:/etc/nginx/conf.d
      - ./data:/data
    networks:
      - stmchat
    
      
volumes:
  mongo_data:

networks:
  stmchat:
